#!/usr/bin/env zsh

# http://peadrop.com/blog/2007/04/07/welcome-to-mr-crystal-ball/
# load and bind prediction
autoload predict-on
zle -N predict-on
zle -N predict-off
bindkey '^Z'   predict-on
bindkey '^X^Z' predict-off
zstyle ':predict' verbose true

# enable line editing
autoload edit-command-line
zle -N edit-command-line
bindkey '^Xe' edit-command-line

export HISTSIZE=100000
export HISTFILE="$HOME/.history"
export SAVEHIST=$HISTSIZE

# Use vim as the editor
export EDITOR=vi
# GNU Screen sets -o vi if EDITOR=vi, so we have to force it back.
set -o emacs

export WORDCHARS='*?[]~&;!$%^<>'

export PATH="$PATH:$HOME/.dotfiles/bin"
